name: Deploy Telegram Bot

on:
  push:
    branches:
      - main # Change to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Adjust based on your requirements

    - name: Install dependencies
      run: npm install

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }} # Use the secret you added
      run: node bot.js
